//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryDAL.DataAccessLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BestOfferDataEntryDBEntities : DbContext
    {
        public BestOfferDataEntryDBEntities()
            : base("name=BestOfferDataEntryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOCATION> LOCATIONS { get; set; }
        public virtual DbSet<OFFER_TYPES> OFFER_TYPES { get; set; }
        public virtual DbSet<PRODUCT_SPECS> PRODUCT_SPECS { get; set; }
        public virtual DbSet<PRODUCT_TYPES> PRODUCT_TYPES { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
        public virtual DbSet<PRODUCTS_CATEGORIES> PRODUCTS_CATEGORIES { get; set; }
        public virtual DbSet<PROVIDER> PROVIDERS { get; set; }
        public virtual DbSet<TIME_FRAMES> TIME_FRAMES { get; set; }
        public virtual DbSet<TIME_FRAMES_FIELDS> TIME_FRAMES_FIELDS { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
