//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryDAL.DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCATION()
        {
            this.PROVIDERS = new HashSet<PROVIDER>();
        }
    
        public int LOCATION_ID { get; set; }
        public string LOCATION_COUNTRY { get; set; }
        public string LOCATION_REGION { get; set; }
        public string LOCATION_CITY { get; set; }
        public string LOCATION_DISTRICT { get; set; }
        public string LOCATION_STREET { get; set; }
        public string LOCATION_COORDINATES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVIDER> PROVIDERS { get; set; }
    }
}
