//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryDAL.DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFER_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OFFER_TYPES()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
        }
    
        public int OFFER_TYPE_ID { get; set; }
        public string OFFER_TYPE_NAME_EN { get; set; }
        public string OFFER_TYPE_NAME_AR { get; set; }
        public string OFFER_TYPE_VALUE { get; set; }
        public string OFFER_TYPE_ATTR_1 { get; set; }
        public string OFFER_TYPE_ATTR_2 { get; set; }
        public string OFFER_TYPE_ATTR_3 { get; set; }
        public string OFFER_TYPE_ATTR_4 { get; set; }
        public string OFFER_TYPE_ATTR_5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
    }
}
