//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryDAL.DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT_TYPES()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
        }
    
        public int TYPE_ID { get; set; }
        public string TYPE_NAME_EN { get; set; }
        public string TYPE_NAME_AR { get; set; }
        public int CATEGORY_ID { get; set; }
        public string TYPE_SPECS { get; set; }
        public string TYPE_ATTR_1 { get; set; }
        public string TYPE_ATTR_2 { get; set; }
        public string TYPE_ATTR_3 { get; set; }
        public string TYPE_ATTR_4 { get; set; }
        public string TYPE_ATTR_5 { get; set; }
        public string TYPE_ATTR_6 { get; set; }
        public string TYPE_ATTR_7 { get; set; }
        public string TYPE_ATTR_8 { get; set; }
        public string TYPE_ATTR_9 { get; set; }
        public string TYPE_ATTR_10 { get; set; }
    
        public virtual PRODUCTS_CATEGORIES PRODUCTS_CATEGORIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
    }
}
