//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryDAL.DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int PRODUCT_ID { get; set; }
        public string PRODUCT_NAME_EN { get; set; }
        public string PRODUCT_NAME_AR { get; set; }
        public int TYPE_ID { get; set; }
        public string PRODUCT_IMAGE { get; set; }
        public int SPECS_ID { get; set; }
        public int PROVIDER_ID { get; set; }
        public int OFFER_TYPE_ID { get; set; }
        public int FRAME_ID { get; set; }
        public string PRODUCT_TAGS { get; set; }
        public bool PRODUCT_EXPIRED { get; set; }
        public string PRODUCT_ATTR_1 { get; set; }
        public string PRODUCT_ATTR_2 { get; set; }
        public string PRODUCT_ATTR_3 { get; set; }
        public string PRODUCT_ATTR_4 { get; set; }
        public string PRODUCT_ATTR_5 { get; set; }
        public string PRODUCT_ATTR_6 { get; set; }
        public string PRODUCT_ATTR_7 { get; set; }
        public string PRODUCT_ATTR_8 { get; set; }
        public string PRODUCT_ATTR_9 { get; set; }
        public string PRODUCT_ATTR_10 { get; set; }
    
        public virtual OFFER_TYPES OFFER_TYPES { get; set; }
        public virtual PRODUCT_SPECS PRODUCT_SPECS { get; set; }
        public virtual PRODUCT_TYPES PRODUCT_TYPES { get; set; }
        public virtual PROVIDER PROVIDER { get; set; }
        public virtual TIME_FRAMES TIME_FRAMES { get; set; }
    }
}
