//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryDAL.DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_SPECS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT_SPECS()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
        }
    
        public int SPECS_ID { get; set; }
        public string SPECS_ATTR_1 { get; set; }
        public string SPECS_ATTR_2 { get; set; }
        public string SPECS_ATTR_3 { get; set; }
        public string SPECS_ATTR_4 { get; set; }
        public string SPECS_ATTR_5 { get; set; }
        public string SPECS_ATTR_6 { get; set; }
        public string SPECS_ATTR_7 { get; set; }
        public string SPECS_ATTR_8 { get; set; }
        public string SPECS_ATTR_9 { get; set; }
        public string SPECS_ATTR_10 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
    }
}
