//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryDAL.DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS_CATEGORIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS_CATEGORIES()
        {
            this.PRODUCT_TYPES = new HashSet<PRODUCT_TYPES>();
        }
    
        public int CATEGORY_ID { get; set; }
        public string CATEGORY_NAME_EN { get; set; }
        public string CATEGORY_NAME_AR { get; set; }
        public string CATEGORY_SPECS { get; set; }
        public string CATEGORY_ATTR_1 { get; set; }
        public string CATEGORY_ATTR_2 { get; set; }
        public string CATEGORY_ATTR_3 { get; set; }
        public string CATEGORY_ATTR_4 { get; set; }
        public string CATEGORY_ATTR_5 { get; set; }
        public string CATEGORY_ATTR_6 { get; set; }
        public string CATEGORY_ATTR_7 { get; set; }
        public string CATEGORY_ATTR_8 { get; set; }
        public string CATEGORY_ATTR_9 { get; set; }
        public string CATEGORY_ATTR_10 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_TYPES> PRODUCT_TYPES { get; set; }
    }
}
