//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryDAL.DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVIDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVIDER()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
        }
    
        public int PROVIDER_ID { get; set; }
        public string PROVIDER_NAME_EN { get; set; }
        public string PROVIDER_NAME_AR { get; set; }
        public string PROVIDER_BUSINESS_AREA { get; set; }
        public int LOCATION_ID { get; set; }
        public string PROVIDER_CONTACTS { get; set; }
        public string PROVIDER_COORDINATOR { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
    }
}
