//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryDAL.DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME_FRAMES_FIELDS
    {
        public int FIELD_ID { get; set; }
        public int FRAME_ID { get; set; }
        public string FIELD_NAME_EN { get; set; }
        public string FIELD_NAME_AR { get; set; }
        public string FIELD_EQUATION { get; set; }
    
        public virtual TIME_FRAMES TIME_FRAMES { get; set; }
    }
}
