//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryDAL.DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME_FRAMES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIME_FRAMES()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
            this.TIME_FRAMES_FIELDS = new HashSet<TIME_FRAMES_FIELDS>();
        }
    
        public int FRAME_ID { get; set; }
        public int FREAME_FIELDS_COUNT { get; set; }
        public string FRAME_NAME_EN { get; set; }
        public string FRAME_NAME_AR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIME_FRAMES_FIELDS> TIME_FRAMES_FIELDS { get; set; }
    }
}
